#!/bin/bash
# SatyaCheck Mobile - Android SDK Setup Script
# Run this after installing Android Studio or command-line tools

set -e

echo "========================================"
echo "SatyaCheck Mobile - Android SDK Setup"
echo "========================================"
echo ""

# Detect OS
if [[ "$OSTYPE" == "linux-gnu"* ]]; then
    SDK_DEFAULT="$HOME/Android/sdk"
    FLUTTER_DEFAULT="$HOME/flutter"
elif [[ "$OSTYPE" == "darwin"* ]]; then
    SDK_DEFAULT="$HOME/Library/Android/sdk"
    FLUTTER_DEFAULT="$HOME/flutter"
elif [[ "$OSTYPE" == "msys" || "$OSTYPE" == "cygwin" ]]; then
    SDK_DEFAULT="$ANDROID_HOME"
    FLUTTER_DEFAULT="C:/flutter"
else
    echo "Unknown OS: $OSTYPE"
    exit 1
fi

# Find Flutter
echo "[1/3] Locating Flutter SDK..."
if command -v flutter &> /dev/null; then
    FLUTTER_PATH=$(dirname $(dirname $(which flutter)))
    echo "✓ Found Flutter at: $FLUTTER_PATH"
else
    echo "✗ Flutter not found. Install from https://flutter.dev/docs/get-started/install"
    exit 1
fi

# Find Android SDK
echo ""
echo "[2/3] Locating Android SDK..."

# Check if Android Studio is installed
if [ -d "$HOME/Android/sdk" ]; then
    SDK_PATH="$HOME/Android/sdk"
    echo "✓ Found Android SDK at: $SDK_PATH"
elif [ -d "$HOME/Library/Android/sdk" ]; then
    SDK_PATH="$HOME/Library/Android/sdk"
    echo "✓ Found Android SDK at: $SDK_PATH"
elif [ -d "$ANDROID_HOME" ]; then
    SDK_PATH="$ANDROID_HOME"
    echo "✓ Found Android SDK at: $SDK_PATH"
else
    echo "✗ Android SDK not found!"
    echo ""
    echo "Install Android Studio from: https://developer.android.com/studio"
    echo "Or download command-line tools from: https://developer.android.com/tools"
    echo ""
    echo "Then run this script again."
    exit 1
fi

# Update local.properties
echo ""
echo "[3/3] Writing local.properties..."

# Convert to Windows paths if on Windows
if [[ "$OSTYPE" == "msys" || "$OSTYPE" == "cygwin" ]]; then
    # Convert / to \\
    SDK_PATH_ESCAPED="${SDK_PATH//\//\\\\}"
    FLUTTER_PATH_ESCAPED="${FLUTTER_PATH//\//\\\\}"
else
    SDK_PATH_ESCAPED="$SDK_PATH"
    FLUTTER_PATH_ESCAPED="$FLUTTER_PATH"
fi

cat > android/local.properties <<EOF
# Auto-generated by SETUP_ANDROID_SDK.sh
sdk.dir=$SDK_PATH_ESCAPED
flutter.sdk=$FLUTTER_PATH_ESCAPED
flutter.buildMode=debug
flutter.versionName=1.0.0
flutter.versionCode=1
EOF

echo "✓ Created android/local.properties"
echo ""
echo "========================================"
echo "Setup Complete!"
echo "========================================"
echo ""
echo "Next steps:"
echo "  cd satyacheck_mobile"
echo "  flutter pub get"
echo "  flutter build apk --debug"
echo "  adb install -r build/app/outputs/apk/debug/app-debug.apk"
echo "  flutter run"
echo ""
