@echo off
REM SatyaCheck Mobile - Android SDK Setup Script (Windows)
REM Run this after installing Android Studio or command-line tools

setlocal enabledelayedexpansion

echo.
echo ========================================
echo SatyaCheck Mobile - Android SDK Setup
echo ========================================
echo.

REM Find Flutter
echo [1/3] Locating Flutter SDK...
for /f "delims=" %%i in ('where flutter 2^>nul') do (
    set FLUTTER_BIN=%%i
)

if defined FLUTTER_BIN (
    for %%A in ("%FLUTTER_BIN%\..\..\..") do set FLUTTER_PATH=%%~fA
    echo ^✓ Found Flutter at: !FLUTTER_PATH!
) else (
    echo ^✗ Flutter not found. Install from https://flutter.dev/docs/get-started/install
    exit /b 1
)

REM Find Android SDK
echo.
echo [2/3] Locating Android SDK...

if exist "%ANDROID_HOME%" (
    set SDK_PATH=%ANDROID_HOME%
    echo ^✓ Found Android SDK at: !SDK_PATH!
) else if exist "%USERPROFILE%\AppData\Local\Android\sdk" (
    set SDK_PATH=%USERPROFILE%\AppData\Local\Android\sdk
    echo ^✓ Found Android SDK at: !SDK_PATH!
) else (
    echo ^✗ Android SDK not found!
    echo.
    echo Install Android Studio from: https://developer.android.com/studio
    echo Or download command-line tools from: https://developer.android.com/tools
    echo.
    echo Then run this script again.
    exit /b 1
)

REM Update local.properties
echo.
echo [3/3] Writing local.properties...

(
    echo # Auto-generated by SETUP_ANDROID_SDK.bat
    echo sdk.dir=!SDK_PATH!
    echo flutter.sdk=!FLUTTER_PATH!
    echo flutter.buildMode=debug
    echo flutter.versionName=1.0.0
    echo flutter.versionCode=1
) > android\local.properties

echo ^✓ Created android\local.properties
echo.
echo ========================================
echo Setup Complete!
echo ========================================
echo.
echo Next steps:
echo   cd satyacheck_mobile
echo   flutter pub get
echo   flutter build apk --debug
echo   adb install -r build\app\outputs\apk\debug\app-debug.apk
echo   flutter run
echo.

endlocal
