import { useState } from "react";
import { Link } from "react-router-dom";

export default function ReportPage() {
  const [copied, setCopied] = useState(false);

  const reportId = "INC-2026-0822-0842";
  const sha256Digest = "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855";

  const handleCopy = () => {
    const text = `SATYACHECK INCIDENT EVIDENCE DOSSIER
Report ID: ${reportId}
Date: ${new Date().toLocaleDateString()}
Incident Type: Deepfake AI Voice Extortion & Digital Arrest Scam
Suspect Caller Number: +91 70428 19043
Targeted Family Member: Rahul Verma (Son)
Audio SHA-256 Digest: ${sha256Digest}
Verification Findings:
- Cloned Voice Probability: 98% Peak (Synthetic Speech)
- Extortion Pattern: Fake Police Arrest & Isolation Demand
- Demanded Payment: Rs 50,000 via Immediate UPI
Transcript: "Papa emergency ho gaya hai, police ne pakad liya hai! Phone kisi ko mat dena, turant 50000 bhejo is UPI ID pe!"
Statutory Filing: National Cybercrime Helpline 1930 & Chakshu (sancharsaathi.gov.in)`;

    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 3000);
  };

  return (
    <div className="max-w-3xl mx-auto space-y-6 pb-12">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-4 border-b border-slate-800">
        <div>
          <div className="flex items-center gap-2 mb-1">
            <span className="px-3 py-1 rounded-full text-xs font-bold bg-red-900/60 text-red-300 border border-red-700/60">
              OFFICIAL FRAUD REPORT
            </span>
            <span className="text-xs text-slate-400 font-mono">
              #{reportId}
            </span>
          </div>
          <h1 className="text-2xl sm:text-3xl font-extrabold text-white">
            Cybercrime Incident Report (1930)
          </h1>
          <p className="text-base text-slate-300 mt-1">
            Official evidence document formatted for the National Cybercrime Portal (1930) or your bank.
          </p>
        </div>

        <div className="flex items-center gap-3">
          <button
            onClick={handleCopy}
            className="px-4 py-2.5 rounded-xl text-sm font-semibold bg-[#1F2937] hover:bg-[#374151] border border-slate-600 text-white transition-all cursor-pointer"
          >
            {copied ? "✓ Copied" : "Copy Text"}
          </button>

          <button
            onClick={() => window.print()}
            className="px-5 py-2.5 rounded-xl text-sm font-bold bg-blue-600 hover:bg-blue-500 text-white transition-all cursor-pointer shadow-md"
          >
            Print / Save PDF
          </button>
        </div>
      </div>

      {/* Main Dossier Card */}
      <div className="p-6 sm:p-8 rounded-2xl bg-[#111827] border border-slate-700 space-y-6 shadow-xl text-base">
        {/* Incident Summary Card */}
        <div className="p-5 rounded-xl bg-[#1F2937] border border-slate-600 grid grid-cols-1 sm:grid-cols-3 gap-4">
          <div>
            <div className="text-xs text-slate-400 uppercase font-semibold">Incident Type</div>
            <div className="font-bold text-red-400 mt-1">AI Voice Extortion</div>
          </div>
          <div>
            <div className="text-xs text-slate-400 uppercase font-semibold">Suspect Caller</div>
            <div className="font-bold text-white mt-1">+91 70428 19043</div>
          </div>
          <div>
            <div className="text-xs text-slate-400 uppercase font-semibold">Targeted Member</div>
            <div className="font-bold text-white mt-1">Rahul Verma (Son)</div>
          </div>
        </div>

        {/* Forensic Evidence Breakdown */}
        <div className="space-y-3">
          <h2 className="text-sm font-bold uppercase tracking-wider text-slate-300">
            1. Evidence Findings & AI Voice Detection
          </h2>

          <div className="space-y-3">
            <div className="p-4 rounded-xl bg-[#1F2937] border border-slate-600 space-y-1">
              <strong className="text-red-300 block font-bold text-base">
                Synthetic Speech Detected (98% Confidence):
              </strong>
              <p className="text-slate-300 text-sm leading-relaxed">
                Neural vocoder acoustic artifacts confirm the caller's voice was generated by an AI cloning system rather than a real human.
              </p>
            </div>

            <div className="p-4 rounded-xl bg-[#1F2937] border border-slate-600 space-y-1">
              <strong className="text-red-300 block font-bold text-base">
                Extortion & Isolation Demand:
              </strong>
              <p className="text-slate-300 text-sm leading-relaxed">
                Caller demanded strict isolation ("Don't hand phone to anyone") and immediate Rs 50,000 UPI transfer under a fake police arrest claim.
              </p>
            </div>
          </div>
        </div>

        {/* Verbatim Audio Transcript */}
        <div className="space-y-2">
          <h2 className="text-sm font-bold uppercase tracking-wider text-slate-300">
            2. Call Transcript (Hindi / Devanagari)
          </h2>
          <div className="p-4 rounded-xl bg-[#1F2937] border border-slate-600 space-y-2">
            <div className="italic text-white text-base">
              "Papa emergency ho gaya hai, police ne pakad liya hai! Phone kisi ko mat dena, turant 50000 bhejo is UPI ID pe!"
            </div>
            <div className="text-xs text-slate-400 pt-2 border-t border-slate-700">
              English translation: "Papa an emergency happened, police have caught me! Don't give the phone to anyone, send 50,000 immediately to this UPI ID!"
            </div>
          </div>
        </div>

        {/* Next Steps for the User */}
        <div className="p-6 rounded-xl bg-blue-950/40 border border-blue-600/50 space-y-3">
          <div className="font-bold text-blue-200 text-base">
            How to File This Report with Authorities:
          </div>
          <ol className="list-decimal pl-5 space-y-2 text-slate-200 text-sm">
            <li>
              <strong>Call Helpline 1930 immediately:</strong> Quote this incident to freeze the scammer's bank account or UPI ID.
            </li>
            <li>
              <strong>Submit online at cybercrime.gov.in:</strong> Upload this printed PDF under "Financial Fraud / Impersonation".
            </li>
            <li>
              <strong>Report on Chakshu (sancharsaathi.gov.in):</strong> Blocks the scammer's SIM card across all telecom networks.
            </li>
          </ol>
        </div>

        {/* Back Link */}
        <div className="pt-3 border-t border-slate-800 flex items-center justify-between text-sm">
          <Link to="/" className="text-blue-400 hover:underline font-semibold no-underline">
            ← Return to Call Checking
          </Link>
          <span className="text-slate-400 text-xs">
            SatyaCheck Secure Evidence System
          </span>
        </div>
      </div>
    </div>
  );
}
