import { useState } from "react";
import { Link } from "react-router-dom";
import { GlassButton } from "@/components/ui/glass-button";
import { Copy, Check, Printer } from "lucide-react";

export default function ReportPage() {
  const [copied, setCopied] = useState(false);

  const reportId = "INC-2026-0822-0842";
  const sha256Digest = "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855";

  const handleCopy = () => {
    const text = `SATYACHECK INCIDENT EVIDENCE DOSSIER
Report ID: ${reportId}
Date: ${new Date().toLocaleDateString()}
Incident Type: Deepfake AI Voice Extortion & Digital Arrest Scam
Suspect Caller Number: +91 70428 19043
Targeted Family Member: Rahul Verma (Son)
Audio SHA-256 Digest: ${sha256Digest}
Verification Findings:
- Cloned Voice Probability: 98% Peak (Synthetic Speech)
- Extortion Pattern: Fake Police Arrest & Isolation Demand
- Demanded Payment: Rs 50,000 via Immediate UPI
Transcript: "Papa emergency ho gaya hai, police ne pakad liya hai! Phone kisi ko mat dena, turant 50000 bhejo is UPI ID pe!"
Statutory Filing: National Cybercrime Helpline 1930 & Chakshu (sancharsaathi.gov.in)`;

    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 3000);
  };

  return (
    <div className="max-w-5xl mx-auto space-y-6 pb-12">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-4 border-b border-[var(--border-subtle)]">
        <div>
          <div className="flex items-center gap-2 mb-1">
            <span className="px-2.5 py-0.5 rounded-full text-xs font-bold bg-[var(--danger-bg)] text-[var(--danger-text)] border border-[var(--danger-border)] font-mono">
              OFFICIAL FRAUD REPORT
            </span>
            <span className="text-xs text-[var(--text-muted)] font-mono">
              #{reportId}
            </span>
          </div>
          <h1 className="text-2xl sm:text-3xl font-extrabold text-[var(--text-primary)] font-mono">
            Cybercrime Incident Report (1930)
          </h1>
          <p className="text-sm sm:text-base text-[var(--text-secondary)] mt-1">
            Official evidence document formatted for the National Cybercrime Portal (1930) or your bank.
          </p>
        </div>

        <div className="flex items-center gap-2.5">
          <GlassButton
            onClick={handleCopy}
            variant="secondary"
            size="sm"
            label={copied ? "Copied" : "Copy Text"}
            icon={copied ? <Check className="w-3.5 h-3.5 mr-1 text-emerald-400" /> : <Copy className="w-3.5 h-3.5 mr-1" />}
          />

          <GlassButton
            onClick={() => window.print()}
            variant="default"
            size="sm"
            label="Print / Save PDF"
            icon={<Printer className="w-3.5 h-3.5 mr-1" />}
          />
        </div>
      </div>

      {/* Main Dossier Card */}
      <div className="sec-card p-6 sm:p-8 space-y-6 text-sm">
        {/* Incident Summary Card */}
        <div className="p-4 rounded-lg bg-[var(--bg-secondary)] border border-[var(--border-default)] grid grid-cols-1 sm:grid-cols-3 gap-4">
          <div>
            <div className="text-xs text-[var(--text-muted)] uppercase font-semibold font-mono">Incident Type</div>
            <div className="font-bold text-[var(--danger)] mt-0.5 text-base font-mono">AI Voice Extortion</div>
          </div>
          <div>
            <div className="text-xs text-[var(--text-muted)] uppercase font-semibold font-mono">Suspect Caller</div>
            <div className="font-bold text-[var(--text-primary)] mt-0.5 font-mono text-base">+91 70428 19043</div>
          </div>
          <div>
            <div className="text-xs text-[var(--text-muted)] uppercase font-semibold font-mono">Targeted Member</div>
            <div className="font-bold text-[var(--text-primary)] mt-0.5 text-base font-mono">Rahul Verma (Son)</div>
          </div>
        </div>

        {/* Forensic Evidence Breakdown */}
        <div className="space-y-2.5">
          <h2 className="text-xs font-bold uppercase tracking-wider text-[var(--text-secondary)] font-mono">
            1. Evidence Findings & AI Voice Detection
          </h2>

          <div className="space-y-2">
            <div className="p-3.5 rounded-lg bg-[var(--bg-secondary)] border border-[var(--border-subtle)] space-y-1">
              <strong className="text-[var(--danger-text)] block font-bold text-sm font-mono">
                Synthetic Speech Detected (98% Confidence):
              </strong>
              <p className="text-[var(--text-secondary)] text-xs leading-relaxed">
                Neural vocoder acoustic artifacts confirm the caller's voice was generated by an AI cloning system rather than a real human.
              </p>
            </div>

            <div className="p-3.5 rounded-lg bg-[var(--bg-secondary)] border border-[var(--border-subtle)] space-y-1">
              <strong className="text-[var(--danger-text)] block font-bold text-sm font-mono">
                Extortion & Isolation Demand:
              </strong>
              <p className="text-[var(--text-secondary)] text-xs leading-relaxed">
                Caller demanded strict isolation ("Don't hand phone to anyone") and immediate Rs 50,000 UPI transfer under a fake police arrest claim.
              </p>
            </div>
          </div>
        </div>

        {/* Verbatim Audio Transcript */}
        <div className="space-y-2">
          <h2 className="text-xs font-bold uppercase tracking-wider text-[var(--text-secondary)] font-mono">
            2. Call Transcript (Hindi / Devanagari)
          </h2>
          <div className="p-4 rounded-lg bg-[var(--bg-secondary)] border border-[var(--border-default)] space-y-1.5">
            <div className="italic text-[var(--text-primary)] text-sm">
              "Papa emergency ho gaya hai, police ne pakad liya hai! Phone kisi ko mat dena, turant 50000 bhejo is UPI ID pe!"
            </div>
            <div className="text-xs text-[var(--text-muted)] pt-2 border-t border-[var(--border-subtle)]">
              English translation: "Papa an emergency happened, police have caught me! Don't give the phone to anyone, send 50,000 immediately to this UPI ID!"
            </div>
          </div>
        </div>

        {/* Next Steps for the User */}
        <div className="p-5 rounded-lg bg-[var(--bg-secondary)] border border-[var(--border-default)] space-y-2.5">
          <div className="font-bold text-[var(--text-primary)] text-sm font-mono">
            How to File This Report with Authorities:
          </div>
          <ol className="list-decimal pl-5 space-y-1.5 text-[var(--text-secondary)] text-xs leading-relaxed">
            <li>
              <strong className="text-[var(--text-primary)]">Call Helpline 1930 immediately:</strong> Quote this incident to freeze the scammer's bank account or UPI ID.
            </li>
            <li>
              <strong className="text-[var(--text-primary)]">Submit online at cybercrime.gov.in:</strong> Upload this printed PDF under "Financial Fraud / Impersonation".
            </li>
            <li>
              <strong className="text-[var(--text-primary)]">Report on Chakshu (sancharsaathi.gov.in):</strong> Blocks the scammer's SIM card across all telecom networks.
            </li>
          </ol>
        </div>

        {/* Back Link */}
        <div className="pt-3 border-t border-[var(--border-subtle)] flex items-center justify-between text-xs">
          <Link to="/" className="no-underline">
            <GlassButton
              variant="secondary"
              size="sm"
              label="← Return to Call Checking"
            />
          </Link>
          <span className="text-[var(--text-muted)] font-mono">
            SatyaCheck Secure Evidence System
          </span>
        </div>
      </div>
    </div>
  );
}
