import { Link } from 'react-router-dom';
import { ArrowUpRight, Phone, Smartphone, ShieldQuestion } from 'lucide-react';
import { PageIntro, External } from '../components/UI';
import { bands } from '../lib/api';
export default function Guide() {
  return <div className="subpage guide"><PageIntro eyebrow="A little context helps" title="Clarity over certainty." description="A screening result can help you ask better questions. It can’t make the decision for you."/>
    <div className="guide-layout"><div><section className="guide-block"><h2>A result is a starting point.</h2>{Object.entries(bands).map(([key, band]) => <div className="band-explainer" key={key}><span className={`band ${band.tone}`}>{band.label}</span><p>{band.description}</p></div>)}</section><section className="guide-block"><Smartphone size={28}/><h2>Two devices. One clearer conversation.</h2><p>To check a call, put it on speaker and use a second device nearby to record a clip. A phone in a cellular call cannot give this app that call’s audio. It can report that it is recording while delivering silence.</p><p>You can also upload a saved recording or voice note. Only use recordings you have permission to analyse.</p><Link to="/" className="text-link">Open the listening desk<ArrowUpRight size={17}/></Link></section><section className="guide-block"><ShieldQuestion size={28}/><h2>What stays, and where.</h2><p>Recordings are sent to your configured screening service. Enrolled voiceprints and stored reports are managed by that service. Ask its operator about access, retention and deletion.</p><p>The report list in this interface lasts for the current page session. Refreshing clears it. Keep a real report’s session ID or download the evidence to retrieve it later.</p></section></div><aside className="guide-action paper"><span className="eyebrow">When something feels wrong</span><h2>You can always<br/>take a pause.</h2><ol><li>Don’t send money or share an OTP under pressure.</li><li>Hang up. Call back on a number you already trust.</li><li>Ask a family member to help verify the request.</li></ol><a className="button solid" href="tel:1930"><Phone size={17}/>Call 1930</a><External href="https://cybercrime.gov.in">Cybercrime reporting portal</External><small>SatyaCheck is a screening aid, not an official complaint or a legal determination.</small></aside></div>
  </div>;
}
