import { useEffect, useState } from 'react';
import { Link, useParams, useNavigate } from 'react-router-dom';
import { motion } from 'motion/react';
import { ArrowLeft, ArrowRight, ArrowUpRight, AudioLines, Check as CheckIcon, Copy, Download, FileText, Fingerprint, MessageCircle, Printer, Search, ShieldQuestion } from 'lucide-react';
import { bands, bandFor, request, readResult, safeLink, when, type Check } from '../lib/api';
import { useLab } from '../lib/store';
import { Button, ErrorNote, External, PageIntro } from '../components/UI';

function download(check: Check) {
  const file = new Blob([JSON.stringify({ sample: check.sample, recording: check.name, ...check.result }, null, 2)], { type: 'application/json' });
  const url = URL.createObjectURL(file); const link = document.createElement('a'); link.href = url; link.download = `satyacheck-${check.result.session_id.replace(/[^a-zA-Z0-9_-]/g,'_')}.json`; link.click(); window.setTimeout(() => URL.revokeObjectURL(url), 1000);
}
export function Reports() {
  const navigate = useNavigate(); const { checks } = useLab(); const [id, setId] = useState('');
  return <div className="subpage"><PageIntro eyebrow="Your evidence library" title="Clarity, kept together." description="Revisit your checks, inspect the evidence, and take your next step with context." action={<Link className="button ivory" to="/">New check<ArrowUpRight size={18}/></Link>}/>
    <div className="reports-layout"><section className="report-library"><div className="section-line"><h2>This session <span className="count">{checks.length}</span></h2><span className="subtle">Cleared when this page is refreshed</span></div>
    {checks.length ? <div className="report-list">{checks.map(check => { const band = bands[bandFor(check.result)]; return <Link className="report-list-item" key={check.result.session_id} to={`/reports/${encodeURIComponent(check.result.session_id)}`}><span className="report-icon"><FileText size={24} strokeWidth={1.4}/></span><div><strong>{check.name}</strong><small>{check.sample ? 'Illustrative sample' : when(check.result.timestamp)} · {check.result.transcript.detected_language}</small></div><span className={`band ${band.tone}`}>{band.label}</span><ArrowUpRight size={20}/></Link>; })}</div> : <div className="library-empty"><div className="empty-paper"><FileText size={44} strokeWidth={1}/><i/><i/><i/></div><h2>Your next clear picture starts here.</h2><p>Check a recording to create a report with the signals, transcript and sources behind it.</p><Link className="text-link" to="/">Check your first recording<ArrowRight size={17}/></Link></div>}
    </section><aside className="retrieve-panel paper"><Search size={26} strokeWidth={1.4}/><h2>Already have a report?</h2><p>Use its session ID to retrieve it from your screening service.</p><form action={`/reports/${encodeURIComponent(id.trim())}`} onSubmit={e => { e.preventDefault(); if (id.trim()) navigate(`/reports/${encodeURIComponent(id.trim())}`); }}><label htmlFor="report-id">Session ID</label><input id="report-id" value={id} onChange={e => setId(e.target.value)} placeholder="Paste a session ID" required/><Button type="submit">Find report<ArrowRight size={17}/></Button></form><small>Sample reports are available only in the current session.</small></aside></div>
  </div>;
}
export function ReportRoute() {
  const { id = '' } = useParams(); const { checks, save } = useLab();
  const known = checks.find(check => check.result.session_id === id);
  const [loaded, setLoaded] = useState<Check | null>(null); const [error, setError] = useState(''); const [retry, setRetry] = useState(0);
  useEffect(() => {
    setLoaded(null); setError(''); if (known) return;
    if (id.startsWith('sample_')) { setError('This sample report belonged to an earlier page session. Open a new sample from the listening desk.'); return; }
    const controller = new AbortController();
    void request<unknown>(`/api/screen/${encodeURIComponent(id)}`, { signal: controller.signal }, 15000).then(response => {
      if (controller.signal.aborted) return;
      const parsed = response.ok ? readResult(response.data) : response;
      if (!parsed.ok) { setError(parsed.error); return; }
      if (parsed.data.session_id !== id) { setError('The service returned a different report. Please verify the session ID.'); return; }
      const check = { result: parsed.data, name: 'Saved recording', sample: false }; setLoaded(check); save(check);
    }); return () => controller.abort();
  }, [id, retry, known, save]);
  const check = known || loaded;
  if (check) return <Evidence check={check}/>;
  return <div className="subpage"><Link to="/reports" className="text-link"><ArrowLeft size={17}/>Back to reports</Link><div className="report-loading">{error ? <><h1>This report isn’t available yet.</h1><ErrorNote>{error}</ErrorNote><Button variant="outline" onClick={() => setRetry(n => n + 1)}>Try again</Button><Link className="text-link" to="/">Return to the listening desk<ArrowRight size={17}/></Link></> : <div role="status"><div className="loading-line"/><h2>Bringing the evidence together…</h2><p>Retrieving your report from the screening service.</p></div>}</div></div>;
}
function Evidence({ check }: { check: Check }) {
  const d = check.result; const band = bandFor(d); const config = bands[band]; const insufficient = band === 'insufficient';
  const [tab, setTab] = useState('overview'); const [copied, setCopied] = useState(false); const [copyError, setCopyError] = useState('');
  const actions = d.fusion.recommended_actions.length ? d.fusion.recommended_actions : ['Call back on a number you already trust before acting on an unexpected request.'];
  async function copy() {
    try { await navigator.clipboard.writeText(`${check.sample ? 'SAMPLE REPORT — NOT AN ANALYSIS OF YOUR AUDIO\n' : ''}SatyaCheck · ${config.label}\n${insufficient ? 'No score: insufficient audio' : `Trust: ${Math.round(d.fusion.trust_score)}/100`}\n${config.description}\n${actions.join('\n')}\nSession: ${d.session_id}`); setCopied(true); setCopyError(''); } catch { setCopyError('Clipboard access is unavailable. Download the report or use Print instead.'); }
  }
  const duration = Math.max(1, ...d.spoof.timeline.map(s => s.end_s));
  const signalData = [
    { name: 'Identity', icon: Fingerprint, value: d.speaker.verdict === 'match' ? 'A familiar match' : d.speaker.verdict === 'mismatch' ? 'Voice mismatch' : 'Not identified', body: d.speaker.matched_person_name || 'No enrolled person verified', risk: d.fusion.identity_risk, abstains: d.fusion.mode === 'authority_check' || d.speaker.verdict === 'unknown' },
    { name: 'Authenticity', icon: AudioLines, value: `${Math.round(d.spoof.median_score * 100)}% median`, body: 'Synthetic speech signal, considered alongside intent', risk: d.fusion.authenticity_risk_effective, abstains: false },
    { name: 'Intent', icon: MessageCircle, value: `${d.script.incriminating_markers.length} concerning · ${d.script.exculpatory_markers.length} reassuring`, body: d.script.intent_summary || 'No intent summary returned', risk: d.fusion.intent_risk, abstains: false },
  ];
  return <article className={`evidence-page result-${config.tone}`}>
    <div className="report-toolbar"><Link className="text-link" to="/reports"><ArrowLeft size={17}/>Your reports</Link><div><Button variant="ghost" onClick={copy}>{copied ? <CheckIcon size={16}/> : <Copy size={16}/>} {copied ? 'Copied' : 'Copy summary'}</Button><Button variant="outline" onClick={() => window.print()}><Printer size={16}/>Print / save PDF</Button><Button variant="outline" onClick={() => download(check)}><Download size={16}/>JSON</Button></div></div>
    {copyError && <ErrorNote>{copyError}</ErrorNote>}
    {check.sample && <div className="sample-notice" role="note"><ShieldQuestion size={18}/><p><strong>Sample report.</strong> An illustration of the evidence view. This is not an analysis of your audio.</p></div>}
    <div className="evidence-heading"><p className="eyebrow">The whole picture</p><div className="recording-label"><FileText size={15}/><span>{check.name}</span><span>{when(d.timestamp)}</span></div></div>
    <section className="verdict-layout"><div className="verdict-copy"><span className={`band ${config.tone}`}>{config.label}</span><h1 tabIndex={-1}>{config.title}</h1><p>{config.description}</p><span className="mode-note">{d.fusion.mode === 'authority_check' ? 'Authority check · Identity not verified' : 'Identity check · Compared with enrolled voices'}</span></div>
    <div className={`score-dial ${config.tone}`} role="img" aria-label={insufficient ? 'No score: insufficient audio' : `Trust score ${Math.round(d.fusion.trust_score)} out of 100. Higher means more trust, not a probability or guarantee.`}><svg viewBox="0 0 220 220" aria-hidden="true"><circle className="dial-track" cx="110" cy="110" r="94"/><circle className="dial-value" cx="110" cy="110" r="94" strokeDasharray={`${insufficient ? 0 : d.fusion.trust_score / 100 * 590.6} 590.6`}/></svg><div><span>Trust score</span><strong>{insufficient ? '—' : Math.round(d.fusion.trust_score)}{!insufficient && <small>/100</small>}</strong><span>{insufficient ? 'Not reported' : 'Higher means more trust'}</span></div></div></section>
    <section className="next-step paper"><div><span className="eyebrow">Your next step</span><h2>{insufficient ? 'Try a clearer recording.' : actions[0]}</h2><ul>{(insufficient ? [d.quality.reason || 'Record more clear speech in a quiet room.'] : actions.slice(1)).map((action,i) => <li key={i}>{action}</li>)}</ul>{d.fusion.vernacular_warning && <p className="vernacular" lang="hi">{d.fusion.vernacular_warning}</p>}</div>{d.fusion.challenge_question ? <aside><MessageCircle size={22}/><span className="eyebrow">A question only they would know</span><p>{d.fusion.challenge_question.question_text}</p><small>Use alongside an independent callback.</small></aside> : <Link className="button solid" to="/">{insufficient ? 'Try another recording' : 'Start a new check'}<ArrowUpRight size={17}/></Link>}</section>
    <nav className="evidence-tabs" role="tablist" aria-label="Report details">{['overview','transcript','references'].map((name,i) => <button key={name} role="tab" id={`report-tab-${name}`} aria-selected={tab === name} aria-controls={`report-${name}`} tabIndex={tab === name ? 0 : -1} onClick={() => setTab(name)} onKeyDown={e => { const names = ['overview','transcript','references']; if (['ArrowLeft','ArrowRight','Home','End'].includes(e.key)) { e.preventDefault(); const next = e.key === 'Home' ? 0 : e.key === 'End' ? 2 : (i + (e.key === 'ArrowLeft' ? 2 : 1)) % 3; setTab(names[next]); document.getElementById(`report-tab-${names[next]}`)?.focus(); } }}>{name}{tab === name && <motion.span className="tab-line" layoutId="report-tab-line"/>}</button>)}</nav>
    <section id="report-overview" className="report-pane" role="tabpanel" aria-labelledby="report-tab-overview" hidden={tab !== 'overview'}>
      {!insufficient && <><div className="signal-cards">{signalData.map(s => <section key={s.name} className="signal-card"><s.icon size={27} strokeWidth={1.3}/><h2>{s.name}</h2><strong>{s.value}</strong><p>{s.body}</p><div className="risk-track"><span style={{ transform: `scaleX(${s.abstains ? 0 : s.risk})` }}/></div><small>{s.abstains ? 'Identity abstains · unknown is neutral' : `Effective risk ${Math.round(s.risk * 100)}/100 · lower is better`}</small></section>)}</div>
      <section className="timeline-panel"><div className="section-line"><h2>Authenticity, across the conversation.</h2><span>Segment model scores · not fraud probability</span></div>{d.spoof.timeline.length ? <div className="signal-timeline" role="img" aria-label="Synthetic speech scores over time. Exact values follow.">{d.spoof.timeline.map((segment,i) => <span key={i} title={`${segment.start_s}–${segment.end_s}s: ${Math.round(segment.score * 100)}%`} className={segment.is_synthetic ? 'synthetic' : ''} style={{ left: `${segment.start_s / duration * 100}%`, width: `${(segment.end_s-segment.start_s) / duration * 100}%`, transform: `scaleY(${Math.max(.03,segment.score)})` }}/>)}</div> : <p>No segment timeline was returned.</p>}<div className="timeline-scale"><span>0s</span><span>{duration.toFixed(1)}s</span></div><dl className="timeline-stats"><div><dt>Median</dt><dd>{Math.round(d.spoof.median_score * 100)}<small>%</small></dd></div><div><dt>Peak</dt><dd>{Math.round(d.spoof.peak_score * 100)}<small>%</small></dd></div><div><dt>Longest synthetic run</dt><dd>{d.spoof.max_synth_run_s.toFixed(1)}<small>sec</small></dd></div></dl><details className="segment-values"><summary>Exact segment values</summary><table><thead><tr><th>Time</th><th>Model score</th><th>Segment</th></tr></thead><tbody>{d.spoof.timeline.map((s,i) => <tr key={i}><td>{s.start_s}–{s.end_s}s</td><td>{Math.round(s.score*100)}%</td><td>{s.is_synthetic ? 'Synthetic signal' : 'Ordinary signal'}</td></tr>)}</tbody></table></details></section></>}
      <div className="quality-strip"><h2>Recording quality</h2><div><span>Clear speech</span><strong>{d.quality.speech_duration_s.toFixed(1)}s</strong><small>Minimum {d.quality.min_speech_threshold_s}s</small></div><div><span>Signal-to-noise</span><strong>{d.quality.snr_db.toFixed(1)} dB</strong><small>Minimum {d.quality.min_snr_threshold_db} dB</small></div><span className={`band ${d.quality.passed ? 'neutral' : 'caution'}`}>{d.quality.passed ? 'Quality gate passed' : 'More audio needed'}</span></div>
    </section>
    <section id="report-transcript" className="report-pane" role="tabpanel" aria-labelledby="report-tab-transcript" hidden={tab !== 'transcript'}><div className="section-line"><h2>The words behind the result.</h2><span>{d.transcript.detected_language} · Automatic transcript</span></div><blockquote className="transcript">{d.transcript.text || 'No transcript was returned.'}</blockquote><p className="subtle">Transcription can contain errors. Compare it with the original recording.</p><div className="marker-columns">{([{ title: 'Raises concern', data: d.script.incriminating_markers, tone: 'danger' }, { title: 'Supports verification', data: d.script.exculpatory_markers, tone: 'positive' }] as const).map(group => <section key={group.title}><h3>{group.title}</h3>{group.data.length ? group.data.map((m,i) => <div className={`marker ${group.tone}`} key={i}><q>{m.matched_text}</q><p>{m.description}</p></div>) : <p className="subtle">No markers returned in this category.</p>}</section>)}</div></section>
    <section id="report-references" className="report-pane" role="tabpanel" aria-labelledby="report-tab-references" hidden={tab !== 'references'}><div className="section-line"><h2>Every finding, explained.</h2><span>Evidence supplied by the screening service</span></div>{d.fusion.reason_codes.length ? d.fusion.reason_codes.map((reason,i) => { const url = safeLink(reason.citation_url); return <section className="reason" key={`${reason.code}-${i}`}><span className="reason-signal">{reason.signal}</span><div><h3>{reason.code.replaceAll('_',' ').toLowerCase()}</h3><p>{reason.explanation}</p><dl><div><dt>Observed</dt><dd>{reason.value}</dd></div><div><dt>Reference</dt><dd>{reason.threshold || 'No threshold supplied'}</dd></div></dl>{url ? <External href={url}>{reason.citation_title || 'Open cited source'}</External> : <span className="subtle">No external citation supplied.</span>}</div></section>; }) : <p>No reason codes were returned.</p>}</section>
    <footer className="evidence-foot"><p>A trust score is supporting evidence, not a probability, guarantee or legal determination.</p><dl><div><dt>Session</dt><dd>{d.session_id}</dd></div><div><dt>Audio SHA-256</dt><dd>{d.audio_sha256 || 'Not supplied'}</dd></div></dl></footer>
  </article>;
}
