import { useEffect, useRef, useState, type FormEvent } from 'react';
import { ArrowRight, AudioLines, Fingerprint, Plus, RefreshCw, Trash2, Users } from 'lucide-react';
import { AnimatePresence, motion, useReducedMotion } from 'motion/react';
import AudioPicker from '../components/AudioPicker';
import { Button, ErrorNote, Modal, PageIntro, ease } from '../components/UI';
import { request, when, type Person } from '../lib/api';

export default function Voices() {
  const [people, setPeople] = useState<Person[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [revision, setRevision] = useState(0);
  const [enrolling, setEnrolling] = useState<Person | 'new' | null>(null); const [removing, setRemoving] = useState<Person | null>(null); const [removeBusy, setRemoveBusy] = useState(false); const [removeError, setRemoveError] = useState(''); const [notice, setNotice] = useState('');
  const reduced = useReducedMotion();
  useEffect(() => {
    const controller = new AbortController(); setLoading(true); setError('');
    void request<unknown>('/api/persons', { signal: controller.signal }, 15000).then(response => {
      if (controller.signal.aborted) return; setLoading(false);
      if (!response.ok) { setError(response.error); return; }
      if (!Array.isArray(response.data) || response.data.some(p => !p || typeof p.person_id !== 'string' || typeof p.name !== 'string' || typeof p.relation !== 'string' || (p.voiceprints != null && (!Array.isArray(p.voiceprints) || p.voiceprints.some((v: { duration_s?: unknown }) => typeof v?.duration_s !== 'number'))))) { setError('The voice list could not be read. Refresh to try again.'); return; }
      setPeople(response.data);
    }); return () => controller.abort();
  }, [revision]);
  async function remove() {
    if (!removing || removeBusy) return; setRemoveBusy(true); setRemoveError('');
    const result = await request(`/api/persons/${encodeURIComponent(removing.person_id)}`, { method: 'DELETE' }, 15000); setRemoveBusy(false);
    if (!result.ok) { setRemoveError(result.error); return; }
    setPeople(current => current.filter(p => p.person_id !== removing.person_id)); setNotice(`${removing.name} was removed from known voices.`); setRemoving(null);
  }
  function initials(name: string) { return Array.from(new Intl.Segmenter('hi', { granularity: 'grapheme' }).segment(name.trim()))[0]?.segment || '?'; }
  return <div className="subpage"><PageIntro eyebrow="Your circle, recognised" title="Some voices feel like home." description="Give a familiar voice a reference. Enroll family and friends, with their permission, for more meaningful identity checks." action={<Button className="ivory" onClick={() => setEnrolling('new')}><Plus size={18}/>Enroll a voice</Button>}/>
    <section className="voices-summary"><div className="circle-symbol"><Users size={28}/></div><p><strong>{people.length} {people.length === 1 ? 'voice' : 'voices'}</strong><span>in your circle</span></p><span>A match helps verify a person.<br/>It never guarantees a request is safe.</span><button className="icon-button" onClick={() => setRevision(n => n + 1)} disabled={loading} aria-label="Refresh voices"><RefreshCw size={18} className={loading ? 'spinner' : ''}/></button></section>
    {notice && <p className="success-note" role="status">{notice}</p>}
    {error && <ErrorNote>{error}<Button variant="ghost" onClick={() => setRevision(n => n + 1)}>Try again</Button></ErrorNote>}
    {loading ? <div className="voices-skeleton" role="status" aria-label="Loading known voices"><span/><span/><span/></div> : !error && !people.length ? <section className="voices-empty"><div className="empty-circle" aria-hidden="true"><Fingerprint size={80} strokeWidth={.65}/><i/><i/></div><div><p className="eyebrow">Start with someone close</p><h2>Recognition begins<br/>with one voice.</h2><p>A quiet room. A minute of natural speech.<br/>One more way to look out for each other.</p><Button className="ivory" onClick={() => setEnrolling('new')}>Add your first voice<Plus size={18}/></Button></div></section> : <div className="voice-grid"><AnimatePresence>{people.map((person,i) => <motion.article layout={!reduced} initial={{ opacity: 0, transform: reduced ? 'none' : 'translateY(10px)' }} animate={{ opacity: 1, transform: 'translateY(0)' }} exit={{ opacity: 0 }} transition={{ duration: .2, ease }} className="voice-card" key={person.person_id}><div className="voice-card-top"><span className={`voice-avatar color-${i % 3}`} lang="hi">{initials(person.name)}</span><button className="icon-button" aria-label={`Remove ${person.name}`} onClick={() => { setRemoving(person); setRemoveError(''); }}><Trash2 size={17}/></button></div><h2>{person.name}</h2><p>{person.relation || 'Known person'}</p><div className="voice-card-meta"><span><AudioLines size={15}/>{person.voiceprints?.length ? `${person.voiceprints.length} voiceprint${person.voiceprints.length === 1 ? '' : 's'}` : 'No voiceprint confirmed'}</span><span>{person.created_at ? when(person.created_at) : 'Date unavailable'}</span></div><Button variant="outline" onClick={() => setEnrolling(person)}>Re-record voice<ArrowRight size={16}/></Button></motion.article>)}</AnimatePresence><button className="add-voice-tile" onClick={() => setEnrolling('new')}><span><Plus size={25}/></span><strong>Make your circle a little closer.</strong><small>Enroll another voice</small></button></div>}
    <div className="privacy-footnote"><Fingerprint size={22}/><p>Voiceprints are stored by your configured screening service. Ask your service operator about access and retention. You can remove a known voice here.</p></div>
    {enrolling && <EnrollDialog person={enrolling === 'new' ? null : enrolling} close={() => setEnrolling(null)} saved={person => { setPeople(current => [person, ...current.filter(p => p.person_id !== person.person_id)]); setNotice(`${person.name}’s voiceprint was confirmed by the service.`); setError(''); setEnrolling(null); }}/>} 
    {removing && <Modal title="Remove this known voice?" close={() => { if (!removeBusy) setRemoving(null); }}><div className="modal-body"><p><strong>{removing.name}</strong> will no longer be available for future identity comparisons. You can enroll their voice again later.</p>{removeError && <ErrorNote>{removeError}</ErrorNote>}<div className="modal-actions"><Button variant="outline" disabled={removeBusy} onClick={() => setRemoving(null)}>Keep voice</Button><Button busy={removeBusy} onClick={remove}>Remove voice<Trash2 size={16}/></Button></div></div></Modal>}
  </div>;
}
function EnrollDialog({ person, close, saved }: { person: Person | null; close: () => void; saved: (person: Person) => void }) {
  const [name, setName] = useState(person?.name || ''); const [relation, setRelation] = useState(person?.relation || 'Family'); const [phone, setPhone] = useState(person?.phone_number || '');
  const [question, setQuestion] = useState(''); const [answer, setAnswer] = useState(''); const [language, setLanguage] = useState('English'); const [file, setFile] = useState<File | null>(null); const [consent, setConsent] = useState(false); const [capturing, setCapturing] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const active = useRef<AbortController | null>(null); useEffect(() => () => active.current?.abort(), []);
  async function submit(event: FormEvent) {
    event.preventDefault(); if (!file || !consent || !name.trim() || capturing || active.current) return;
    if (Boolean(question.trim()) !== Boolean(answer.trim())) { setError('Add both a verification question and its answer, or leave both empty.'); return; }
    const controller = new AbortController(); active.current = controller; setBusy(true); setError('');
    const body = new FormData(); body.append('name', name.trim()); body.append('relation', relation.trim()); body.append('file', file); if (person) body.append('person_id', person.person_id); if (phone.trim()) body.append('phone_number', phone.trim()); if (question.trim()) body.append('shared_secrets', JSON.stringify([{ question: question.trim(), answer: answer.trim() }]));
    const response = await request<Person>('/api/enroll', { method: 'POST', body, signal: controller.signal }); if (controller.signal.aborted) return;
    active.current = null; setBusy(false);
    if (!response.ok) { setError(response.error); return; }
    const p = response.data;
    if (!p || typeof p.person_id !== 'string' || typeof p.name !== 'string' || typeof p.relation !== 'string' || !Array.isArray(p.voiceprints) || !p.voiceprints.length) { setError('The service did not confirm a saved voiceprint. Try a clearer recording.'); return; }
    saved(p);
  }
  return <Modal title={person ? 'Refresh a familiar voice' : 'Bring a voice into your circle'} close={close} wide><form className="enrollment-form" onSubmit={submit}><p>Around 60 seconds of natural speech in a quiet room gives your service a useful reference.</p><fieldset disabled={busy}><div className="field-grid"><label>Name<input autoFocus required value={name} onChange={e => setName(e.target.value)} placeholder="What do you call them?"/></label><label>Relationship<input value={relation} onChange={e => setRelation(e.target.value)} placeholder="Family, friend, colleague"/></label></div><div className="speaking-prompt"><div><span>Something to say</span><div className="language-switch">{['English','हिन्दी'].map(l => <button key={l} type="button" aria-pressed={language === l} onClick={() => setLanguage(l)}>{l}</button>)}</div></div><p lang={language === 'English' ? 'en' : 'hi'}>{language === 'English' ? '“Hello, I’m recording my voice so my family can recognise me. If you receive an unexpected request in my name, call me on the number you know. Now I’ll tell you a little about my day…”' : '“नमस्ते, मैं अपनी आवाज़ रिकॉर्ड कर रहा हूँ ताकि मेरे परिवार वाले मुझे पहचान सकें। अगर मेरे नाम पर कोई अचानक पैसे माँगे, तो मेरे परिचित नंबर पर फोन करके पुष्टि करें। अब मैं अपने दिन के बारे में बताता हूँ…”'}</p></div><AudioPicker enrollment file={file} onFile={setFile} disabled={busy} onBusy={setCapturing}/><details className="optional-form"><summary>Add a phone number or shared question <span>Optional</span></summary><label>Known phone number<input type="tel" value={phone} onChange={e => setPhone(e.target.value)} placeholder="+91"/></label><label>A question only they would know<input value={question} onChange={e => setQuestion(e.target.value)} placeholder="Where did we go on our last family trip?"/></label><label>Expected answer<input value={answer} onChange={e => setAnswer(e.target.value)} autoComplete="off"/></label></details><label className="consent"><input type="checkbox" checked={consent} onChange={e => setConsent(e.target.checked)}/><span>This person has agreed to have their voice enrolled for future comparisons.</span></label></fieldset>{error && <ErrorNote>{error}</ErrorNote>}<div className="modal-actions"><small>Enrollment is complete only when the service confirms a voiceprint.</small><Button type="submit" busy={busy} disabled={!file || !consent || !name.trim() || capturing}>Save voiceprint<ArrowRight size={17}/></Button></div></form></Modal>;
}
